document: feedback-pipeline-workload
version: 1
data:
  name: Other packages from SST CS Aps
  description: Unsorted tools owned by CS Apps SST
  maintainer: sst_cs_apps

  packages:
  - less

  labels:
  - eln
